name: multiple runners and choose jobs
on: 
    workflow_dispatch:
        inputs:
            runner:
                description: 'Choose the runner to execute the job'
                required: true
                default: 'ubuntu-latest'
                type: choice
                options:
                    - ubuntu-latest
                    - windows-latest
                    - macos-latest
            job-name:
                description: 'Enter the multiple job names to execute (comma-separated)'
                required: true
                type: string
                
jobs:
    build-job:
        if: contains(github.event.inputs.job-name, 'build-job')
        # select the runner based on the input
        runs-on: ${{ github.event.inputs.runner }}
        steps:
            - name: Build step
              run: echo "Running build job on ${{ github.event.inputs.runner }}"
    test-job:
        if: contains(github.event.inputs.job-name, 'test-job')
        # select the runner based on the input
        runs-on: ${{ github.event.inputs.runner }}
        steps:
            - name: Test step
              run: echo "Running test job on ${{ github.event.inputs.runner }}"
    deploy-job:
        if: contains(github.event.inputs.job-name, 'deploy-job')
        # select the runner based on the input
        runs-on: ${{ github.event.inputs.runner }}
        steps:
            - name: Deploy step
              run: echo "Running deploy job on ${{ github.event.inputs.runner }}"
