name: Build nodejs application using github actions
on: 
  push:  # run on every push to the master branch
    branches:
        - master
  workflow_dispatch: # run manually
jobs:
   buildnodejs:
    runs-on: self-hosted  # we will use self hosted runner to run the job, we can also use github hosted runner by specifying the os like ubuntu-latest, windows-latest, macos-latest
    steps:  # all steps will be exeucted ont he runner
        - name: Checkout code
          uses: actions/checkout@v6 
        - name: Install nodejs of version 18 and npm
          uses: actions/setup-node@v6
          with:
            node-version: 18
        - name: Install dependencies using npm
          run: npm install
        - name: run tests using npm
          run: npm test
        - name: build the application using npm
          run: npm run build
